# Generated by Django 4.2 on 2023-05-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField()),
                ('user_id', models.CharField()),
                ('session_id', models.CharField()),
                ('session_start_time', models.DateTimeField()),
                ('session_end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_multiplier', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('categ_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.CharField(blank=True, max_length=15, null=True)),
                ('code', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_weight_amount', models.FloatField(blank=True, null=True)),
                ('gross_weight_unit', models.FloatField(blank=True, null=True)),
                ('hierarchies', models.JSONField(blank=True, null=True)),
                ('net_weight_amount', models.FloatField(blank=True, null=True)),
                ('net_weight_unit', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('packaging', models.CharField(blank=True, max_length=50, null=True)),
                ('regulated_name', models.CharField(blank=True, max_length=30, null=True)),
                ('requires_best_before_date', models.BooleanField(blank=True, default=False, null=True)),
                ('requires_meat_info', models.BooleanField(blank=True, null=True)),
                ('trade_item_descriptor', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=10, null=True)),
                ('validation_status', models.CharField(blank=True, max_length=20, null=True)),
                ('vat_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('vat', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=20)),
                ('trade_item_unit_descriptor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('best_before_date', models.DateTimeField(blank=True, null=True, verbose_name='bbd')),
                ('comment', models.TextField(blank=True, null=True)),
                ('country_of_disassembly', models.CharField(blank=True, null=True)),
                ('country_of_rearing', models.CharField(blank=True, null=True)),
                ('country_of_slaughtering', models.CharField(blank=True, null=True)),
                ('slaughterhouse_registration', models.CharField(blank=True, null=True)),
                ('lot_number', models.CharField(blank=True, null=True)),
                ('cutting_plant_registration', models.CharField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_feed.item')),
                ('product_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='product_feed.feed')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='related_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='product_feed.relatedproduct'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('code',)},
        ),
    ]
