# Generated by Django 4.2 on 2023-05-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
    ]
