# Generated by Django 4.2 on 2023-05-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_feed', '0003_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='related_products',
            field=models.ManyToManyField(related_name='items', to='product_feed.relatedproduct'),
        ),
    ]
