# Generated by Django 4.2 on 2023-05-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_feed', '0004_alter_item_related_products'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
    ]
