# Generated by Django 4.2 on 2023-05-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_feed', '0005_alter_item_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='trade_item_descriptor',
            new_name='trade_item_unit_descriptor',
        ),
    ]
