# Generated by Django 4.2 on 2023-05-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_feed', '0007_alter_product_product_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gross_weight_amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gross_weight_unit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='net_weight_amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='net_weight_unit',
        ),
        migrations.AddField(
            model_name='item',
            name='gross_weight',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='net_weight',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
