# Generated by Django 4.2 on 2023-05-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_feed', '0008_remove_item_gross_weight_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='best_before_date',
            new_name='bbd',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='country_of_slaughtering',
            new_name='country_of_slaughter',
        ),
        migrations.AddField(
            model_name='item',
            name='trade_item_unit_descriptor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
