# Generated by Django 4.2 on 2023-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_feed', '0011_alter_item_edeka_article_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='edeka_article_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
